In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
import os #Define path of files and directory
from skimage.io import imread #used for reading images
from sklearn.model_selection import train_test_split
from skimage.transform import resize # to resize all the images to same size

In [ ]:
os.listdir('/content/drive/MyDrive/MaskFiles')

['WithMask', 'WithoutMask']

In [ ]:
len(os.listdir('/content/drive/MyDrive/MaskFiles/WithMask'))

483

In [ ]:
len(os.listdir('/content/drive/MyDrive/MaskFiles/WithoutMask'))

509

In [ ]:
maskpath='/content/drive/MyDrive/MaskFiles/WithMask'
for i in os.listdir(maskpath):
  print(i)

1163.png
1835.png
1834.png
1607.png
1767.png
1821.png
1606.png
1611.png
1612.png
1820.png
178.png
1573.png
1565.png
1559.png
1558.png
153.png
152.png
1407.png
1413.png
1439.png
147.png
1405.png
1362.png
1404.png
1388.png
1363.png
1389.png
1203.png
1361.png
1175.png
1174.png
740.png
635.png
608.png
609.png
557.png
580.png
556.png
595.png
53.png
542.png
51.png
45.png
423.png
46.png
408.png
422.png
392.png
385.png
351.png
393.png
350.png
224.png
225.png
3.png
230.png
231.png
219.png
1836.png
187.png
190.png
Augmented_128_7642144.png
Augmented_125_3402457.png
Augmented_11_641260.png
Augmented_116_7228146.png
Augmented_109_7550607.png
Augmented_115_6749830.png
Augmented_117_9479645.png
Augmented_120_536902.png
Augmented_106_3549951.png
Augmented_105_2879173.png
Augmented_105_2237800.png
Augmented_104_6573201.png
971.png
92.png
998.png
90.png
91.png
85.png
84.png
86.png
807.png
783.png
796.png
79.png
782.png
769.png
768.png
741.png
742.png
754.png
Augmented_178_1929527.png
Augmented_175_7003

In [ ]:
nomaskpath='/content/drive/MyDrive/MaskFiles/WithoutMask'
for i in os.listdir(nomaskpath):
  print(i)

1215.png
1203.png
1201.png
1202.png
1175.png
1188.png
1177.png
1161.png
1163.png
1174.png
1029.png
1014.png
1.png
1000.png
1148.png
1149.png
1028.png
1160.png
1001.png
1015.png
1217.png
152.png
153.png
147.png
1558.png
1564.png
1559.png
150.png
146.png
1413.png
144.png
1438.png
1439.png
1216.png
1377.png
1362.png
1361.png
1375.png
1376.png
1349.png
1363.png
1411.png
1410.png
1404.png
1405.png
1407.png
1388.png
1822.png
1821.png
1834.png
1820.png
1809.png
1798.png
1799.png
1808.png
178.png
1773.png
1766.png
1767.png
1611.png
1612.png
1607.png
1613.png
1570.png
1639.png
1772.png
1565.png
1567.png
1573.png
1606.png
1605.png
1571.png
1598.png
2086.png
2085.png
2052.png
2078.png
2079.png
2045.png
2050.png
2051.png
1997.png
2044.png
1996.png
184.png
1835.png
187.png
185.png
190.png
1836.png
1940.png
1954.png
193.png
1941.png
191.png
1983.png
1968.png
1969.png
1982.png
1955.png
2326.png
2291.png
2290.png
2284.png
2285.png
2253.png
2247.png
225.png
2252.png
224.png
2246.png
219.png
2131.png
21

In [ ]:
flat_data_arr=[] #collect input samples
target_arr=[] #Collect output samples
categories=['WithMask','WithoutMask']
dirpath='/content/drive/MyDrive/MaskFiles'

In [ ]:
for i in categories:
  path=os.path.join(dirpath,i)
  for img in os.listdir(path):
    img_arr=imread(os.path.join(path,img))
    img_resize=resize(img_arr,(150,150,3))
    flat_data_arr.append(img_resize.flatten())
    target_arr.append(categories.index(i))
  print("Loaded completely",i)



Loaded completely WithMask
Loaded completely WithoutMask


In [ ]:
#Create arrays of input and outputs
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)
#Create dataframe from input dsamples
df=pd.DataFrame(flat_data)
df.shape

(992, 67500)

In [ ]:
#Add outputsample to dataframe
df['Target']=target_data
df.shape

(992, 67501)

In [ ]:
x=df.iloc[:,:-1]
x

0         1         2         3         4         5         6      \
0    0.140871  0.127956  0.115267  0.144729  0.130064  0.117959  0.145373   
1    0.514108  0.495849  0.491539  0.523551  0.506372  0.502224  0.532995   
2    0.885913  0.811468  0.757208  0.911595  0.844471  0.794435  0.918932   
3    0.105680  0.107710  0.052428  0.102191  0.106658  0.052501  0.098702   
4    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
987  0.958946  0.842973  0.669862  0.933592  0.817618  0.644507  0.878073   
988  0.047851  0.028243  0.012557  0.052108  0.032500  0.016814  0.058339   
989  0.371264  0.179107  0.052911  0.368168  0.176011  0.048717  0.361804   
990  0.158904  0.110747  0.064237  0.182819  0.131211  0.086427  0.196235   
991  0.416497  0.400000  0.301556  0.423399  0.402301  0.301556  0.425346   

        7         8         9      ...     67490     67491     67492  \
0    0.130416  0.118408  0.141514  ...  0.107144  0.145310  0.090698   
1    0.516894  0.512910  0.530816  ...  0.276862  0.385921  0.283754   
2    0.853900  0.805071  0.893251  ...  0.310826  0.550022  0.443094   
3    0.105607  0.052573  0.099507  ...  0.131712  0.147399  0.123869   
4    0.000000  0.000000  0.000000  ...  0.017098  0.040784  0.021176   
..        ...       ...       ...  ...       ...       ...       ...   
987  0.762099  0.589306  0.802627  ...  0.178289  0.278759  0.315753   
988  0.038731  0.023045  0.062745  ...  0.224523  0.613110  0.464091   
989  0.169255  0.039843  0.359294  ...  0.196471  0.406824  0.258196   
990  0.138980  0.093490  0.175137  ...  0.428842  0.787216  0.582110   
991  0.399921  0.294170  0.421135  ...  0.184021  0.250575  0.258549   

        67493     67494     67495     67496     67497     67498     67499  
0    0.086212  0.151010  0.095009  0.089700  0.185213  0.120872  0.110632  
1    0.281823  0.360462  0.261296  0.260325  0.335004  0.238837  0.238827  
2    0.336416  0.546170  0.437412  0.329105  0.532688  0.417525  0.303514  
3    0.131712  0.147399  0.123869  0.131712  0.147399  0.123869  0.131712  
4    0.009412  0.035137  0.017569  0.005804  0.032732  0.016366  0.004601  
..        ...       ...       ...       ...       ...       ...       ...  
987  0.321348  0.490541  0.531443  0.537855  0.645401  0.687977  0.696301  
988  0.217032  0.603660  0.454641  0.207582  0.596915  0.447895  0.200837  
989  0.173882  0.422944  0.273925  0.191572  0.433947  0.284927  0.202574  
990  0.409255  0.784642  0.575470  0.398441  0.787368  0.576229  0.396232  
991  0.185935  0.251791  0.263556  0.189046  0.254092  0.265856  0.191346  

[992 rows x 67500 columns]

In [ ]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
987    1
988    1
989    1
990    1
991    1
Name: Target, Length: 992, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [ ]:
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1])

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy score is",accuracy_score(y_test,y_pred))

Accuracy score is 0.9296482412060302


In [ ]:
#To make predictions for a new image withmask
path1='/content/drive/MyDrive/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvczc1LWppci0wMzM1LWV5ZV8xLWt6YXRtMGl1LmpwZw.webp'#assign path
img=imread(path1)#read image
img=resize(img,(150,150,3)).flatten().reshape(1,-1)#resize the image
model.predict(img)

array([0])

In [ ]:
#To make predictions for a new image of unmasked
path2='/content/drive/MyDrive/withoutmask.jpg'#assign path
img=imread(path2)#read image
img=resize(img,(150,150,3)).flatten().reshape(1,-1)#resize the image
model.predict(img)

array([0])